changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes
      labels:
        - major
        - breaking-change
    - title: Enhancements
      labels:
        - "*"
