name: release-pypi

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Build dist
        run: |
          python -m pip install --upgrade pip build
          python -m build
      - name: Publish to pypi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
